app = "wechsel"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"
  build-target = "runtime"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "stop"
  force_https = true
  internal_port = 8787
  min_machines_running = 0

[[mounts]]
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "10GB"
  auto_extend_size_threshold = 80
  destination = "/data"
  source = "data"

[processes]
  app = "node dist/server/server/index.js"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
